DROP DATABASE IF EXISTS yoga;

CREATE DATABASE yoga DEFAULT CHARACTER SET utf8mb4;

CREATE TABLE adresses (
	id INT UNSIGNED AUTO_INCREMENT,
    rue VARCHAR(38) NOT NULL,
    code_postal CHAR(5) NOT NULL,
    ville VARCHAR(38)
);

CREATE TABLE salles (
	id INT UNSIGNED AUTO_INCREMENT,
    nom_salle VARCHAR(30) NOT NULL,
    capacite TINYINT UNSIGNED NOT NULL DEFAULT 10,
    adresse_id INT UNSIGNED NOT NULL
);